
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package AnalisisReporte;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT1 = 7;
  public static final int PAR_DER = 13;
  public static final int DIFERENCIA = 26;
  public static final int POR = 36;
  public static final int CONST = 24;
  public static final int IGUALACION = 25;
  public static final int ENTERO = 3;
  public static final int CASE = 46;
  public static final int PRI = 10;
  public static final int DOSPT = 19;
  public static final int FOR = 42;
  public static final int PUB = 9;
  public static final int NOT = 33;
  public static final int AND = 31;
  public static final int IGUAL = 18;
  public static final int OR = 32;
  public static final int CHAR1 = 8;
  public static final int IF = 40;
  public static final int MAYOR_Q = 28;
  public static final int LLAV_IZQ = 14;
  public static final int ID = 2;
  public static final int VOI = 11;
  public static final int EOF = 0;
  public static final int DECIMAL = 4;
  public static final int CADENA_SIMP = 6;
  public static final int MENOR_Q = 27;
  public static final int CLASE = 21;
  public static final int error = 1;
  public static final int COMA = 16;
  public static final int CADENA = 5;
  public static final int MODULO = 39;
  public static final int MENOS = 35;
  public static final int BREAK = 47;
  public static final int PAR_IZQ = 12;
  public static final int SWITCH = 45;
  public static final int POTENCIA = 38;
  public static final int ELSE = 41;
  public static final int WHILE = 44;
  public static final int DEFAULT = 48;
  public static final int MAYOR_IGUAL = 30;
  public static final int LET = 22;
  public static final int PTCOMA = 17;
  public static final int LLAV_DER = 15;
  public static final int MENOR_IGUAL = 29;
  public static final int DIVISION = 37;
  public static final int VAR = 23;
  public static final int DO = 43;
  public static final int PRINT = 20;
  public static final int MAS = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "CADENA_SIMP",
  "INT1",
  "CHAR1",
  "PUB",
  "PRI",
  "VOI",
  "PAR_IZQ",
  "PAR_DER",
  "LLAV_IZQ",
  "LLAV_DER",
  "COMA",
  "PTCOMA",
  "IGUAL",
  "DOSPT",
  "PRINT",
  "CLASE",
  "LET",
  "VAR",
  "CONST",
  "IGUALACION",
  "DIFERENCIA",
  "MENOR_Q",
  "MAYOR_Q",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "AND",
  "OR",
  "NOT",
  "MAS",
  "MENOS",
  "POR",
  "DIVISION",
  "POTENCIA",
  "MODULO",
  "IF",
  "ELSE",
  "FOR",
  "DO",
  "WHILE",
  "SWITCH",
  "CASE",
  "BREAK",
  "DEFAULT"
  };
}

