
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package AnalisisReporte;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONSOLA = 24;
  public static final int PAR_DER = 8;
  public static final int ENTER = 18;
  public static final int DIFERENCIA = 21;
  public static final int CONST = 19;
  public static final int POR = 32;
  public static final int IGUALACION = 20;
  public static final int ENTERO = 3;
  public static final int CASE = 42;
  public static final int DOSPT = 14;
  public static final int FOR = 38;
  public static final int NOT = 29;
  public static final int AND = 27;
  public static final int IGUAL = 13;
  public static final int OR = 28;
  public static final int IF = 36;
  public static final int MAYOR_Q = 23;
  public static final int LLAV_IZQ = 9;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int DECIMAL = 4;
  public static final int CADENA_SIMP = 6;
  public static final int MENOR_Q = 22;
  public static final int CLASE = 15;
  public static final int error = 1;
  public static final int COMA = 11;
  public static final int CADENA = 5;
  public static final int MODULO = 35;
  public static final int MENOS = 31;
  public static final int REQUIRE = 45;
  public static final int BREAK = 43;
  public static final int PAR_IZQ = 7;
  public static final int SWITCH = 41;
  public static final int POTENCIA = 34;
  public static final int ELSE = 37;
  public static final int WHILE = 40;
  public static final int DEFAULT = 44;
  public static final int MAYOR_IGUAL = 26;
  public static final int LET = 16;
  public static final int PTCOMA = 12;
  public static final int LLAV_DER = 10;
  public static final int MENOR_IGUAL = 25;
  public static final int DIVISION = 33;
  public static final int VAR = 17;
  public static final int DO = 39;
  public static final int MAS = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "CADENA_SIMP",
  "PAR_IZQ",
  "PAR_DER",
  "LLAV_IZQ",
  "LLAV_DER",
  "COMA",
  "PTCOMA",
  "IGUAL",
  "DOSPT",
  "CLASE",
  "LET",
  "VAR",
  "ENTER",
  "CONST",
  "IGUALACION",
  "DIFERENCIA",
  "MENOR_Q",
  "MAYOR_Q",
  "CONSOLA",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "AND",
  "OR",
  "NOT",
  "MAS",
  "MENOS",
  "POR",
  "DIVISION",
  "POTENCIA",
  "MODULO",
  "IF",
  "ELSE",
  "FOR",
  "DO",
  "WHILE",
  "SWITCH",
  "CASE",
  "BREAK",
  "DEFAULT",
  "REQUIRE"
  };
}

